# -*- coding: utf-8 -*-
"""ckm_genai_probe_rag.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10SCtGTnwK7N2ctrln4RzT6ln2s7LaI2A

# Cardiovascular-Kidney-Metabolic Syndrome: a genai messaging probe

### Access Popular LLMs via Google-Colab-AI Without an API Key

This notebook keeps the original Ollama-in-Colab setup **intact and unchanged**, and adds
two layers on top of it:

1. **RAG** — grounds `llama3.1:8b` in PDF documents (starting with the 2026 AHA/ACC/ADA/ASN
   CKM guideline), extendable to any future PDFs.
2. **Messaging evaluator** — scores the grounded model on simulated CKM patient-portal
   messages loaded from `ckm_patients.json`, each with structured EHR/lab context and an
   expected triage result.

Nothing from the original notebook is removed. `generate_ollama_response()`, the version
probe, and the "capital of France" test all remain and still work; the RAG and evaluator
sit alongside them.

**Layout**

| Part | Sections | Origin |
|---|---|---|
| Ollama setup, model tests | 1–5 | **original, unchanged** |
| RAG over PDFs | 6–11 | new |
| Patient messaging evaluator | 12–16 | new |

> **Runtime:** select a **GPU** runtime (`Runtime > Change runtime type`), then run top to bottom.

---
# Part I — Notebook setup
## More memory

Users who have purchased one of Colab's paid plans have access to high-memory VMs when they are available. More powerful GPUs are always offered with high-memory VMs.

You can see how much memory you have available at any time by running the following code cell. If the execution result of running the code cell below is "Not using a high-RAM runtime", then you can enable a high-RAM runtime via `Runtime > Change runtime type` in the menu. Then select High-RAM in the Runtime shape toggle button. After, re-execute the code cell.
### 1. Install required packages
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -r requirements.txt

import psutil

ram_gb = psutil.virtual_memory().total / 1e9
print('Your runtime has {:.1f} gigabytes of available RAM\n'.format(ram_gb))

if ram_gb < 20:
  print('Not using a high-RAM runtime')
else:
  print('You are using a high-RAM runtime!')

"""### 2. Install Ollama in Colab
#### Longer runtimes

All Colab runtimes are reset after some period of time (which is faster if the runtime isn't executing code). Colab Pro and Pro+ users have access to longer runtimes than those who use Colab free of charge.

#### Background execution

Colab Pro+ users have access to background execution, where notebooks will continue executing even after you've closed a browser tab. This is always enabled in Pro+ runtimes as long as you have compute units available.

##### Running Ollama directly in Colab

*   List item
*   List item



To run Ollama directly within your Colab environment, you'll need to install it and then pull the desired model. For larger models, ensure you have a GPU runtime enabled (`Runtime > Change runtime type` and select a GPU accelerator).
"""

!sudo apt-get update && sudo apt-get install -y zstd
!curl -fsSL https://ollama.com/install.sh | sh

print('Ollama installation script executed.')

# @title Select your desired Ollama model
# You can find more models at https://ollama.com/library
DEFAULT_MODEL = "llama3.1:8b" # @param ["llama2","phi3","mistral","tinyllama","gemma:2b","stable-code","llama3.1","mxbai-embed-large","llama3.1:8b"]

print(f"Selected model: {DEFAULT_MODEL}")



"""### 3. Run Ollama server
After installing Ollama, you need to start the Ollama server. This usually happens automatically upon installation or the first `ollama` command, but explicitly starting it ensures it's running in the background.
"""

import subprocess
import time
import os
import requests

OLLAMA_BINARY_PATH = "/usr/local/bin/ollama"
OLLAMA_HOST = "http://localhost:11434"

print(f"Ensuring a fresh Ollama server instance at {OLLAMA_HOST}...")

# Terminate any existing Ollama processes to prevent port conflicts
try:
    # Find PIDs of processes listening on port 11434 and kill them
    pids_output = subprocess.check_output(f"lsof -i tcp:11434 | grep LISTEN | awk '{{print $2}}'", shell=True, text=True)
    pids = [int(p) for p in pids_output.strip().split('\n') if p]
    if pids:
        print(f"Killing existing Ollama process(es): {pids}")
        for pid in pids:
            os.kill(pid, 9) # Send SIGKILL
            time.sleep(1) # Give it a moment to die
except subprocess.CalledProcessError:
    # This occurs if lsof finds nothing or grep doesn't match 'LISTEN'
    pass # No existing processes to kill
except Exception as e:
    print(f"Warning: Error during attempt to kill old Ollama processes: {e}")

# Try to start Ollama server using subprocess.Popen for background execution
try:
    ollama_process = subprocess.Popen(
        [OLLAMA_BINARY_PATH, 'serve'],
        stdout=subprocess.DEVNULL, # Redirect stdout to DEVNULL for less clutter
        stderr=subprocess.DEVNULL, # Redirect stderr to DEVNULL for less clutter
    )
    print(f"Ollama server process started (PID: {ollama_process.pid}).")

    # Wait for Ollama to be ready
    ready = False
    start_time = time.time()
    timeout = 90 # Increase timeout for Ollama to spin up
    print("Waiting for Ollama server to become ready...")
    while not ready and (time.time() - start_time < timeout):
        try:
            # Use requests for a more robust HTTP check
            # Ollama's root endpoint often returns 404 but indicates server is up
            response = requests.get(f'{OLLAMA_HOST}', timeout=5)
            if response.status_code in [200, 404]: # 404 is fine for base URL of Ollama
                ready = True
        except requests.exceptions.ConnectionError:
            pass # Keep trying
        except requests.exceptions.Timeout:
            pass # Keep trying
        time.sleep(5) # Check every 5 seconds

    if ready:
        print("Ollama server is ready and accessible.")
    else:
        print(f"Error: Ollama server did not become ready within {timeout} seconds.")

except FileNotFoundError:
    print(f"Error: Ollama binary not found at {OLLAMA_BINARY_PATH}. Please ensure Ollama was installed correctly in the previous step.")
except Exception as e:
    print(f"Error starting Ollama server: {e}")

print(f'OLLAMA_HOST is set to: {OLLAMA_HOST}')

# Pull the selected model
# This can take a while depending on the model size and your internet connection.
!{OLLAMA_BINARY_PATH} pull {DEFAULT_MODEL}

print(f'Model {DEFAULT_MODEL} pulled.')

"""### 4. Verify connection and model

Now your Colab environment has Ollama running locally within it, and you can use `urllib.request` to interact with it.
"""

import urllib.request
import urllib.error
import json

# Example: Check if Ollama server is reachable and list models
try:
    with urllib.request.urlopen(f'{OLLAMA_HOST}/api/tags') as response:
        data = json.loads(response.read().decode())
        print(f"Successfully connected to Ollama! Available models: {data.get('models', [])}")
except urllib.error.URLError as e:
    print(f"Could not connect to Ollama: {e}")
    print("Please ensure the Ollama server started correctly in this Colab session.")

import requests, json

resp = requests.get(f'{OLLAMA_HOST}/api/tags')
models = [m['name'] for m in resp.json().get('models', [])]
print(models)  # should include 'llama3.1:8b'

requests.post(f"{OLLAMA_HOST}/api/generate",
              json={"model": DEFAULT_MODEL, "keep_alive": 0})

"""

```
# This is formatted as code
```

### 5. Test the Model"""

import requests
import json

def generate_ollama_response(prompt, model=DEFAULT_MODEL, host=OLLAMA_HOST):
    url = f'{host}/api/generate'
    payload = {
        'model': model,
        'prompt': prompt,
        'stream': False, # Get the full response at once
        "options": {"temperature": 0, "seed": 42}
    }
    headers = {'Content-Type': 'application/json'}

    try:
        response = requests.post(url, headers=headers, data=json.dumps(payload), timeout=60)
        response.raise_for_status() # Raise an exception for HTTP errors
        return response.json()['response'].strip()
    except requests.exceptions.RequestException as e:
        print(f"Error generating response: {e}")
        return None

# Test 1: Ask for the model's version
print(f"Querying '{DEFAULT_MODEL}' for its version...")
version_prompt = "What is your version?"
model_version_response = generate_ollama_response(version_prompt)
if model_version_response:
    print(f"Response for 'What is your version?':\n{model_version_response}\n")

# Test 2: Ask a general knowledge question
print(f"Querying '{DEFAULT_MODEL}' for 'What is the capital of France?'...")
capital_prompt = "What is the capital of France?"
capital_response = generate_ollama_response(capital_prompt)
if capital_response:
    print(f"Response for 'What is the capital of France?':\n{capital_response}")

"""---
# Part II — RAG layer

Everything above still works exactly as before. `generate_ollama_response()` remains
available for ungrounded queries, which is useful as a **baseline**: the evaluator in
Part III can run with RAG on or off to measure what retrieval actually contributes.

#### 6. Configure RAG

The single place to tune the pipeline.

- **`EMBED_MODEL`** — `nomic-embed-text` (768-d) is fast. `mxbai-embed-large` (1024-d, already
  in your model dropdown) gives better recall. *Changing this invalidates the index — delete
  `CHROMA_DIR` and re-ingest.*
- **`CHROMA_DIR`** — `/content` is **wiped when the session ends**. Point at a mounted Drive
  path to persist the index and skip re-embedding each session.
- **`USE_RERANKER`** — reranking is the highest-leverage quality lever after chunking.
"""

CHAT_MODEL  = DEFAULT_MODEL       # reuse the model selected in the @param cell above
EMBED_MODEL = "nomic-embed-text"  # 768-d, fast; "mxbai-embed-large" (1024-d) for higher recall

# Storage. /content is ephemeral on Colab; use a Drive path to persist across sessions.
CHROMA_DIR = "/content/ckm_rag/chroma"
COLLECTION = "ckm_corpus"

# Chunking
CHUNK_TARGET_CHARS  = 1200   # ~300 tokens; balances context against retrieval precision
CHUNK_OVERLAP_CHARS = 200    # carries context across chunk boundaries

# Retrieval
RETRIEVE_K   = 12            # candidates pulled from the vector store
USE_RERANKER = True          # cross-encoder rerank of candidates (recommended)
FINAL_K      = 5             # chunks actually shown to the LLM after reranking
RERANK_MODEL = "cross-encoder/ms-marco-MiniLM-L-6-v2"

# Generation. temperature 0 + fixed seed keeps evaluation runs reproducible.
GEN_OPTIONS = {"temperature": 0, "seed": 42, "num_ctx": 8192}

print("RAG config loaded.")

"""### 7. Install RAG dependencies

| Package | Role |
|---|---|
| `pymupdf` | PDF text extraction with page numbers |
| `chromadb` | Persistent vector store |
| `sentence-transformers` | Cross-encoder reranker (skipped if `USE_RERANKER = False`) |
"""

#%pip -q install pymupdf chromadb
#if USE_RERANKER:
#    %pip -q install sentence-transformers

# The embedding model runs on the same Ollama server started above.
!{OLLAMA_BINARY_PATH} pull {EMBED_MODEL}
print(f"Embedding model {EMBED_MODEL} pulled.")

"""### 8. Set up Ollama helpers for RAG

`generate_ollama_response()` from stays as-is. These two additions cover what RAG
needs and it does not: **batched embeddings**, and a **chat-endpoint** call that accepts a
separate system prompt (`/api/generate` takes a single flat prompt, which makes the grounding
instruction harder to keep separate from the retrieved context).
"""

def embed_texts(texts, model=EMBED_MODEL, host=OLLAMA_HOST, batch_size=64):
    """Return a list of embedding vectors for a list of strings (batched)."""
    if isinstance(texts, str):
        texts = [texts]
    vectors = []
    for i in range(0, len(texts), batch_size):
        batch = texts[i:i + batch_size]
        try:
            # /api/embed is the current batch endpoint
            r = requests.post(f"{host}/api/embed", json={"model": model, "input": batch}, timeout=120)
            r.raise_for_status()
            vectors.extend(r.json()["embeddings"])
        except Exception:
            # Fall back to the older one-at-a-time endpoint
            for t in batch:
                r = requests.post(f"{host}/api/embeddings", json={"model": model, "prompt": t}, timeout=120)
                r.raise_for_status()
                vectors.append(r.json()["embedding"])
    return vectors


# def chat_ollama_response(system, user, model=CHAT_MODEL, host=OLLAMA_HOST, options=None):
#     """Single-turn chat completion with a separate system prompt, via /api/chat."""
#     payload = {
#         "model": model,
#         "messages": [{"role": "system", "content": system}, {"role": "user", "content": user}],
#         "stream": False,
#         "options": options or GEN_OPTIONS,
#     }
#     try:
#         r = requests.post(f"{host}/api/chat", json=payload, timeout=300)
#         r.raise_for_status()
#         return r.json()["message"]["content"].strip()
#     except requests.exceptions.RequestException as e:
#         print(f"Error generating chat response: {e}")
        # return None

def chat_ollama_response(system, user, model=CHAT_MODEL, host=OLLAMA_HOST, options=None):
    """Single-turn chat completion with a separate system prompt, via /api/chat."""
    opts = options or GEN_OPTIONS
    payload = {
        "model": model,
        "messages": [{"role": "system", "content": system}, {"role": "user", "content": user}],
        "stream": False,
        "options": opts,
    }
    r = requests.post(f"{host}/api/chat", json=payload, timeout=300)
    r.raise_for_status()
    body = r.json()
    body["_request_options"] = opts      # not from Ollama; what we sent
    body["_request_model"] = model       # what we asked for, vs body["model"] loaded
    return body["message"]["content"].strip(), body

# def chat_ollama_response(system, user, model=CHAT_MODEL, host=OLLAMA_HOST, options=None):
#     """Single-turn chat completion with a separate system prompt, via /api/chat."""
#     payload = {
#         "model": model,
#         "messages": [{"role": "system", "content": system}, {"role": "user", "content": user}],
#         "stream": False,
#         "options": options or GEN_OPTIONS,
#     }
#     r = requests.post(f"{host}/api/chat", json=payload, timeout=300)
#     r.raise_for_status()
#     body = r.json()
#     return body["message"]["content"].strip(), body

# Smoke test both helpers before spending time on ingestion.
print("embedding dim:", len(embed_texts(["test"])[0]))
print("chat:", chat_ollama_response("Reply in exactly one word.", "Say OK."))

raw, meta = chat_ollama_response("You are terse.", "Say OK.")
print("meta:", meta["prompt_eval_count"], raw)

"""### 9. PDF loading and chunking

`_clean()` handles two artifacts present in the CKM guideline PDF: soft hyphens
(`develop\u00adment`) and line-break hyphenation (`develop-\nment`). Left in, both corrupt
the embedded tokens and degrade retrieval.

**Chunking is done per page**, which keeps page numbers exact for citation, necessary when a
reader has to verify a recommendation against the source guideline.
"""

import os, re, hashlib
import fitz  # PyMuPDF


def _clean(text):
    """Normalize whitespace, drop soft hyphens, de-hyphenate line breaks."""
    text = text.replace("\u00ad", "")                 # soft hyphen
    text = re.sub(r"(\w)-\n(\w)", r"\1\2", text)   # "develop-\nment" -> "development"
    text = re.sub(r"[ \t]+\n", "\n", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def load_pdf_pages(path):
    """Return [(page_number, cleaned_text), ...] for pages that contain text."""
    doc = fitz.open(path)
    pages = []
    for i, page in enumerate(doc):
        txt = _clean(page.get_text("text"))
        if txt:
            pages.append((i + 1, txt))
    doc.close()
    return pages


def chunk_page(text, target=CHUNK_TARGET_CHARS, overlap=CHUNK_OVERLAP_CHARS):
    """Pack paragraphs into ~target-char chunks; hard-split any oversized paragraph."""
    paras = [p.strip() for p in re.split(r"\n\s*\n", text) if p.strip()]
    chunks, buf = [], ""
    for p in paras:
        if len(buf) + len(p) + 1 <= target:
            buf = (buf + "\n" + p).strip()
        else:
            if buf:
                chunks.append(buf)
            if len(p) > target:
                start = 0
                while start < len(p):
                    chunks.append(p[start:start + target])
                    start += max(1, target - overlap)
                buf = ""
            else:
                buf = p
    if buf:
        chunks.append(buf)
    return chunks


def build_chunks(path):
    """Turn one PDF into a list of chunk records with citation metadata."""
    source = os.path.basename(path)
    records = []
    for page_no, page_text in load_pdf_pages(path):
        for idx, chunk in enumerate(chunk_page(page_text)):
            uid = hashlib.sha1(f"{source}|{page_no}|{idx}|{chunk[:80]}".encode()).hexdigest()
            records.append({
                "id": uid,
                "text": chunk,
                "metadata": {"source": source, "page": page_no, "chunk": idx},
            })
    return records

"""### 10. Set up vector store and idempotent ingestion

Chunk IDs are content-derived SHA-1 hashes, so `ingest_documents()` skips anything already
stored rather than re-embedding it. Re-running is cheap and never duplicates. **This is the
extension point** — adding future PDFs is one call.

Cosine distance is set explicitly; Chroma defaults to L2, a poorer fit for text embeddings.
"""

import chromadb

os.makedirs(CHROMA_DIR, exist_ok=True)
_client = chromadb.PersistentClient(path=CHROMA_DIR)
_collection = _client.get_or_create_collection(name=COLLECTION, metadata={"hnsw:space": "cosine"})


def ingest_documents(paths, verbose=True):
    """Ingest one or more PDFs into the vector store. Idempotent."""
    if isinstance(paths, str):
        paths = [paths]

    all_records = []
    for path in paths:
        recs = build_chunks(path)
        all_records.extend(recs)
        if verbose:
            print(f"  {os.path.basename(path)}: {len(recs)} chunks")

    ids = [r["id"] for r in all_records]
    existing = set()
    for i in range(0, len(ids), 500):
        existing.update(_collection.get(ids=ids[i:i + 500]).get("ids", []))
    new = [r for r in all_records if r["id"] not in existing]

    if not new:
        print(f"Nothing new to embed. Collection size: {_collection.count()}")
        return

    if verbose:
        print(f"Embedding {len(new)} new chunks ({len(all_records) - len(new)} already present)...")
    vectors = embed_texts([r["text"] for r in new])

    for i in range(0, len(new), 500):
        batch = new[i:i + 500]
        _collection.upsert(
            ids=[r["id"] for r in batch],
            embeddings=vectors[i:i + 500],
            documents=[r["text"] for r in batch],
            metadatas=[r["metadata"] for r in batch],
        )
    print(f"Ingested. Collection size: {_collection.count()}")

"""### 11. Set up retrieval, reranking, and grounded answers

Two-stage retrieval: embedding similarity casts a wide net (`RETRIEVE_K`), then a
cross-encoder reorders by true query-passage relevance and keeps `FINAL_K`. The bi-encoder
compares query and passage encoded *independently*; the cross-encoder reads both together —
slower, but markedly more accurate. Running it over a shortlist is what makes it affordable.
"""

_reranker = None


def _get_reranker():
    """Lazy-load the cross-encoder so CPU-only sessions can skip the cost."""
    global _reranker
    if _reranker is None:
        from sentence_transformers import CrossEncoder
        print(f"Loading reranker {RERANK_MODEL} ...")
        _reranker = CrossEncoder(RERANK_MODEL)
    return _reranker


def retrieve(question, k=RETRIEVE_K, final_k=FINAL_K, use_reranker=USE_RERANKER):
    """Return the top chunks for a question as a list of dicts."""
    qvec = embed_texts([question])[0]
    res = _collection.query(
        query_embeddings=[qvec],
        n_results=k,
        include=["documents", "metadatas", "distances"],
    )
    hits = [
        {"text": d, "metadata": m, "distance": dist}
        for d, m, dist in zip(res["documents"][0], res["metadatas"][0], res["distances"][0])
    ]

    if use_reranker and hits:
        scores = _get_reranker().predict([(question, h["text"]) for h in hits])
        for h, s in zip(hits, scores):
            h["rerank_score"] = float(s)
        hits.sort(key=lambda h: h["rerank_score"], reverse=True)

    return hits[:final_k]


def _format_context(hits):
    """Render retrieved chunks as [S#] blocks plus a reference list."""
    blocks, refs = [], []
    for i, h in enumerate(hits, 1):
        m = h["metadata"]
        tag = f"S{i}"
        blocks.append(f"[{tag}] (source: {m['source']}, p.{m['page']})\n{h['text']}")
        refs.append(f"[{tag}] {m['source']}, p.{m['page']}")
    return "\n\n".join(blocks), refs


RAG_SYSTEM_PROMPT = (
    "You are a medical expert. You specialize in understanding the urgency of medical queries. Answer ONLY from the "
    "provided context. If the answer is not in the context, say you cannot find "
    "it in the provided documents - do not use outside knowledge and do not "
    "guess. Cite every claim with the bracketed source tags shown in the context "
    "(e.g., [S1], [S2]). Be concise and precise; this may inform clinical "
    "decisions and must be verifiable against the sources."
)


def answer(question, show_sources=True, **retrieval_kwargs):
    """Retrieve, then generate a grounded, cited answer."""
    hits = retrieve(question, **retrieval_kwargs)
    if not hits:
        return "No documents have been ingested yet. Call ingest_documents([...]) first."

    context, refs = _format_context(hits)
    user_prompt = f"Context:\n\n{context}\n\nQuestion: {question}\n\nAnswer (with [S#] citations):"
    reply = chat_ollama_response(RAG_SYSTEM_PROMPT, user_prompt)

    if show_sources:
        reply += "\n\nRetrieved sources:\n" + "\n".join(refs)
    return reply

"""### Ingest the guideline corpus

Upload the PDF via the Colab **Files** pane (or mount Drive), then set the path below.
Expected for the CKM guideline: **109 pages → ~679 chunks**. The first ingestion takes a few
minutes; re-running afterwards is near-instant.
"""

DOCS = [
    "/content/ndumele-et-al-2026-ckm.pdf",
]

# Fail early with a clear message rather than a confusing traceback deep inside fitz.
for p in DOCS:
    if not os.path.exists(p):
        raise FileNotFoundError(f"Not found: {p}\nUpload it via the Files pane and fix the path above.")

ingest_documents(DOCS)

"""### Grounded QA, and the refusal check

A grounded system's most important behaviour is admitting ignorance. The second query asks
something the guideline does not cover — if the model answers it fluently anyway, grounding
is not working.
"""

print(answer("What are the first-line therapies for patients with CKD and type 2 diabetes?"))
print("\n" + "=" * 80 + "\n")
print(answer("What is the recommended treatment protocol for a fractured tibia?"))

"""### Inspect retrieval on its own

Retrieval quality caps answer quality. A wrong answer is usually a retrieval failure, not a
generation failure. Look at what came back before blaming the model.
"""

for h in retrieve("nonsteroidal mineralocorticoid receptor antagonist albuminuria potassium"):
    m = h["metadata"]
    score = h.get("rerank_score")
    score_str = f"rerank={score:.3f}" if score is not None else f"dist={h['distance']:.3f}"
    print(f"[{m['source']} p.{m['page']}] {score_str}")
    print(h["text"][:300].replace("\n", " "), "...\n")

"""---
# Part III — Patient messaging evaluator

### 12. Initialize the synthetic patient corpus

`ckm_patients.json` holds simulated CKM patients, each with structured EHR context (problems,
medications, vitals, labs) and ambiguous patient-portal messages. Every message carries an
`expected` block for automated scoring.

**Schema**

```
patients[]
  patient_id, demographics, ckm_stage, conditions[], medications[], vitals, labs
  messages[]
    message_id, sent_at, text
    expected:
      triage          one of EMERGENT | URGENT | ROUTINE | SELF_CARE   <- scored
      ambiguity       low | moderate | high                            <- stratifier
      requires_ehr    true if free text alone is insufficient          <- stratifier
      rationale_tags  clinical concepts that should drive the decision
      must_reference  terms the rationale should mention               <- scored (recall)
      key_action      reference answer for human review
      probe_note      why this item is in the corpus
```

**The design point.** `CKM-001-M1` and `CKM-002-M1` are near-identical in free text ("tingling
in my hands, legs feel heavy, probably just getting old") but differ by **two triage levels**,
because CKM-001 has K+ 5.4 on finerenone + lisinopril at eGFR 48 while CKM-002 has K+ 4.1,
eGFR 88, and no RASi or MRA. Pairs like this are what separate EHR-grounded reasoning from
pattern matching on symptom words.

All data is synthetic. No real patient information.
"""

import json

PATIENTS_PATH = "/content/ckm_pts_segments_1_staged.json"   # upload via the Files pane

if not os.path.exists(PATIENTS_PATH):
    raise FileNotFoundError(f"Not found: {PATIENTS_PATH}\nUpload ckm_pts_segments_1_staged.json via the Files pane.")

with open(PATIENTS_PATH) as f:
    CORPUS = json.load(f)

TRIAGE_RANK = {lvl["code"]: lvl["rank"] for lvl in CORPUS["triage_levels"]}
TRIAGE_DEFS = "\n".join(f"- {l['code']}: {l['definition']}" for l in CORPUS["triage_levels"])

# Flatten to (patient, message) pairs for iteration.
CASES = [(p, m) for p in CORPUS["patients"] for m in p["messages"]]

print(f"{len(CORPUS['patients'])} patients, {len(CASES)} messages")
print(f"\nTriage levels:\n{TRIAGE_DEFS}")

"""### 13. Render EHR context

The model sees the structured data as a compact text block. `format_ehr()` is the **ablation
switch** for the probe's central question: calling `triage_message(..., use_ehr=False)`
withholds it, so the same message can be scored with and without structured context and the
difference attributed to the EHR.
"""

def format_ehr(patient, use_ckm_stage=True):
    """Render a patient's structured EHR context as a compact text block."""
    demo = patient.get("demographics", {})
    problems = patient.get("problem_list") or []
    diagnoses = patient.get("diagnoses", {}).get("past_year") or []
    meds = patient.get("medications") or []

    lines = [
        f"Age/gender: {demo.get('age', 'unknown')} {demo.get('gender', 'unknown')}",
        f"Problems: {', '.join(problems) if problems else 'none recorded'}",
        f"Past-year diagnoses: {', '.join(diagnoses) if diagnoses else 'none recorded'}",
        f"Medications: {'; '.join(meds) if meds else 'none recorded'}",
    ]
    if use_ckm_stage:
        lines.append(f"CKM stage: {patient.get('ckm_stage_label') or 'not staged'}")
    return "\n".join(lines)

# def format_ehr(patient):
#     """Render a patient's structured EHR context as a compact text block."""
#     d = patient["demographics"]
#     diag = patient["demographics"]
#     lines = [
#         f"Age/gender: {d['age']} {d['gender']}", # Keep
#         f"Problems: {', '.join(patient['problem_list']) if patient['problem_list'] else 'none recorded'}",
#         f"Diagnosis: {', '.join(patient['diagnoses']['past_year']) if patient['diagnoses'] else 'none recorded'}",
#         f"CKM stage: {patient.get('ckm_stage_label', 'not staged')}",
#     ]

#     # if patient["medications"]:
#     #     med_strings = []
#     #     for m in patient["medications"]:
#     #         if isinstance(m, dict):
#     #             # Assume m is a dictionary with 'name', 'dose', 'class', 'started' keys
#     #             med_strings.append(f"{m.get('name', 'N/A')} {m.get('dose', 'N/A')} ({m.get('class', 'N/A')}, started {m.get('started', 'N/A')})")
#     #         else:
#     #             # If m is not a dict, treat it as a simple medication name string
#     #             med_strings.append(str(m))
#     #     meds = "; ".join(med_strings)
#     # else:
#     #     meds = "none recorded"

#     #lines.append(f"Medications: {meds}")

#     return "\n".join(lines)


# print(format_ehr(CORPUS["patients"][0]))

"""### 14. Set up triage function

Assembles patient EHR context + retrieved guideline passages + the message, and requests a
**strict JSON** verdict so scoring is deterministic rather than a prose-parsing exercise.

Three switches, each isolating one contribution:

| Switch | Off means | Measures |
|---|---|---|
| `use_ehr=False` | structured data withheld | what the EHR contributes |
| `use_rag=False` | no guideline passages retrieved | what retrieval contributes |
| both off | free text into the bare model | the original ungrounded baseline |
"""

TRIAGE_SYSTEM = (
    "You are a medical expert reviewing patient-portal messages for a "
    "cardiovascular-kidney-metabolic (CKM) care team. Weigh the patient's structured EHR "
    "data as heavily as the words of the message where patients routinely minimize symptoms, "
    "offer benign explanations, and bury red flags in casual language. Ground clinical "
    "reasoning in the provided guideline context and cite it with [S#] tags where it "
    "applies. Respond with a single JSON object and nothing else, no preamble, no "
    "markdown fences."
)

TRIAGE_TEMPLATE = """Triage levels:
{triage_defs}

Patient EHR context:
{ehr}

Guideline context:
{context}

Patient portal message (sent {sent_at}):
{message}

Return a JSON object with exactly these keys:
{{
  "triage": one of {codes},
  "red_flags": [short strings, the specific findings driving the decision, [] if none],
  "rationale": "2-3 sentences citing EHR values and [S#] guideline tags",
  "recommended_action": "one sentence, what should happen next"
}}"""


def _parse_json_response(raw):
    """Extract a JSON object from a model response, tolerating fences and stray prose."""
    if not raw:
        return None
    text = re.sub(r"^```(?:json)?|```$", "", raw.strip(), flags=re.MULTILINE).strip()
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass
    # Fall back to the outermost brace-delimited span.
    start, end = text.find("{"), text.rfind("}")
    if start != -1 and end > start:
        try:
            return json.loads(text[start:end + 1])
        except json.JSONDecodeError:
            return None
    return None

def triage_message(patient, message, use_ehr=True, use_rag=True, use_ckm_stage=False):
    """Run one message through the model. Returns the parsed verdict plus provenance."""
    if use_rag:
        # Retrieve on the message text, enriched with structured EHR terms only when
        # use_ehr is on: the message alone is often too vague to hit the right
        # guideline section, but enriching it regardless would leak structured data
        # into the EHR-withheld conditions via the retrieval channel.
        parts = [message["text"]]
        if use_ehr:
            parts += patient.get("problem_list", [])
            parts += patient.get("diagnoses", {}).get("past_year", [])
            if use_ckm_stage:
                parts.append(str(patient.get("ckm_stage_label") or ""))
        query = " ".join(p for p in parts if p)
        context, refs = _format_context(retrieve(query))
    else:
        query, context, refs = "", "(no guideline context provided)", []

    user = TRIAGE_TEMPLATE.format(
        triage_defs=TRIAGE_DEFS,
        ehr=format_ehr(patient, use_ckm_stage) if use_ehr else "(structured EHR data withheld)",
        context=context,
        sent_at=message["sent_at"],
        message=message["text"],
        codes=list(TRIAGE_RANK),
    )
 #   raw = chat_ollama_response(TRIAGE_SYSTEM, user)
    raw, meta = chat_ollama_response(TRIAGE_SYSTEM, user)
    return {
        "message_id": message["message_id"],
        "id": patient.get("id", "UNKNOWN_PATIENT_ID"),
        "raw": raw,
        "parsed": _parse_json_response(raw),
        "query": query,
        "retrieved": refs,
        "use_ehr": use_ehr,
        "use_rag": use_rag,
        "use_ckm_stage": use_ckm_stage,
        "prompt_tokens": meta.get("prompt_eval_count"),
        "eval_tokens": meta.get("eval_count"),
        "gen_options": meta["_request_options"],
        "model": meta.get("model", meta["_request_model"]),
    }

# def triage_message(patient, message, use_ehr=True, use_rag=True, use_ckm_stage=False):
#     """Run one message through the model. Returns the parsed verdict plus provenance."""
#     if use_rag:
#         # Retrieve on the message text plus problem list and past-year diagnoses:
#         # the message alone is often too vague to hit the right guideline section.
#         parts = [
#             message["text"],
#             *patient.get("problem_list", []),
#             *patient.get("diagnoses", {}).get("past_year", []),
#         ]
#         if use_ckm_stage:
#             parts.append(str(patient.get("ckm_stage_label") or ""))
#             #print("parts:", parts)
#         context, refs = _format_context(retrieve(" ".join(p for p in parts if p)))
#     else:
#         context, refs = "(no guideline context provided)", []

#     user = TRIAGE_TEMPLATE.format(
#         triage_defs=TRIAGE_DEFS,
#         ehr=format_ehr(patient) if use_ehr else "(structured EHR data withheld)",
#         context=context,
#         sent_at=message["sent_at"],
#         message=message["text"],
#         codes=list(TRIAGE_RANK),
#     )

#     print("context", context)

#     raw = chat_ollama_response(TRIAGE_SYSTEM, user)
#     return {
#         "message_id": message["message_id"],
#         "id": patient.get("id", "UNKNOWN_PATIENT_ID"),
#         "raw": raw,
#         "parsed": _parse_json_response(raw),
#         "retrieved": refs,
#         "use_ehr": use_ehr,
#         "use_rag": use_rag,
#         "use_ckm_stage": use_ckm_stage,
#     }


# Single-case demo: the harder half of the paired probe item.
_p = CORPUS["patients"][0]
_m = _p["messages"][0]
_r = triage_message(_p, _m)
print("MESSAGE:", _m["text"], "\n")
#print("EXPECTED:", _m["expected"]["triage"], "|", _m["expected"]["key_action"], "\n")
print("MODEL:", json.dumps(_r["parsed"], indent=2) if _r["parsed"] else _r["raw"])

"""### 15. Define triage scoring

Four metrics, because plain accuracy hides what matters clinically:

| Metric | Why |
|---|---|
| **Exact accuracy** | headline agreement with the expected label |
| **Under-triage rate** | predicted *less* severe than expected. The dangerous error — a missed EMERGENT is not the same failure as a needless escalation, and accuracy alone treats them identically |
| **Over-triage rate** | predicted more severe. Drives alert fatigue rather than harm |
| **Severity distance** | mean ordinal gap; separates near-misses from wild misses |
| **Reference recall** | fraction of `must_reference` terms appearing in the rationale. Catches a right label reached for the wrong reason |

`severity_distance` uses the ranks declared in the JSON, so adding or reordering triage levels
needs no code change.
"""

import pandas as pd


def score_one(expected, result):
    """Score a single triage result against its expected block."""
    parsed = result["parsed"]
    exp_code = expected["triage"]

    if not parsed or parsed.get("triage") not in TRIAGE_RANK:
        # Unparseable or invalid label is a failure, not a missing value - keep it in the
        # denominator so a model that emits garbage cannot score well by abstaining.
        return {
            "predicted": parsed.get("triage") if parsed else None,
            "expected": exp_code,
            "correct": False,
            "parse_ok": parsed is not None,
            "severity_distance": None,
            "under_triage": None,
            "over_triage": None,
            "reference_recall": 0.0,
        }

    pred_code = parsed["triage"]
    dist = TRIAGE_RANK[pred_code] - TRIAGE_RANK[exp_code]

    # Reference recall over the free-text fields the model produced.
    blob = " ".join([
        parsed.get("rationale", ""),
        parsed.get("recommended_action", ""),
        " ".join(parsed.get("red_flags", []) or []),
    ]).lower()

    return {
        "predicted": pred_code,
        "expected": exp_code,
        "correct": pred_code == exp_code,
        "parse_ok": True,
        "severity_distance": dist,
        "under_triage": dist < 0,
        "over_triage": dist > 0,
    }


def evaluate(cases=CASES, use_ehr=True, use_rag=True, use_ckm_stage=True, verbose=True):
    """Run every case and return a per-message DataFrame."""
    rows = []
    for i, (patient, message) in enumerate(cases, 1):
        if verbose:
            print(f"[{i}/{len(cases)}] {message['message_id']} ...", end=" ")
        result = triage_message(patient, message, use_ehr=use_ehr, use_rag=use_rag, use_ckm_stage=use_ckm_stage)
        scored = score_one(message["expected"], result)
        if verbose:
            mark = "OK  " if scored["correct"] else "MISS"
            print(f"{mark} expected={scored['expected']} predicted={scored['predicted']}")
        rows.append({
            "message_id": message["message_id"],
            "id": patient["id"],
            "use_ehr": use_ehr,
            "use_rag": use_rag,
            "use_ckm_stage": use_ckm_stage,
            **scored,
            "rationale": (result["parsed"] or {}).get("rationale", ""),
            "recommended_action": (result["parsed"] or {}).get("recommended_action", ""),
            "retrieved": "; ".join(result["retrieved"]),
        })
    return pd.DataFrame(rows)


def summarize(df, label=""):
    """Aggregate a results frame into headline metrics."""
    n = len(df)
    return {
        "condition": label,
        "n": n,
        "accuracy": round(df["correct"].mean(), 3),
        "under_triage_rate": round(df["under_triage"].fillna(False).mean(), 3),
        "over_triage_rate": round(df["over_triage"].fillna(False).mean(), 3),
        "mean_abs_severity_distance": round(df["severity_distance"].abs().mean(), 3),
        #"reference_recall": round(df["reference_recall"].dropna().mean(), 3),
        "parse_failure_rate": round(1 - df["parse_ok"].mean(), 3),
    }

"""### Run the full evaluation"""

RESULTS_PATH = "/content/ckm_probe_results_full_all.csv"

results_full = evaluate(use_ehr=True, use_rag=True, use_ckm_stage=True)

display(results_full[["message_id", "expected", "predicted", "correct",
                      "severity_distance"]])

print("\nSummary:", json.dumps(summarize(results_full, "EHR + RAG + CKM Staging Known"), indent=2))

results_full.to_csv(RESULTS_PATH, index=False)

print(f"Wrote {len(results_full)} rows to {RESULTS_PATH}")

# if results are same, maybe try restarting ollama from the beginning
RESULTS_PATH = "/content/ckm_probe_results_full_no_ckm_stg.csv"

results_full = evaluate(use_ehr=True, use_rag=True, use_ckm_stage=False)

display(results_full[["message_id", "expected", "predicted", "correct",
                      "severity_distance"]])

print("\nSummary:", json.dumps(summarize(results_full, "EHR + RAG + CKM Staging Known"), indent=2))

results_full.to_csv(RESULTS_PATH, index=False)

print(f"Wrote {len(results_full)} rows to {RESULTS_PATH}")

user = "What is your purpose?"
a, _ = chat_ollama_response(TRIAGE_SYSTEM, user)
b, _ = chat_ollama_response(TRIAGE_SYSTEM, user)
print("identical:", a == b)

for p in CORPUS["patients"]:
    for m in p["messages"]:
        off = triage_message(p, m, use_ckm_stage=False)
        on  = triage_message(p, m, use_ckm_stage=True)
        changed = off["parsed"].get("triage") != on["parsed"].get("triage")
        print(f"{p['id']} {m['message_id']} {changed}")

off["parsed"].get("triage")

on["parsed"].get("triage")

"""### Where does it fail?

Under-triage on an `EMERGENT` item is the finding that matters most — `CKM-003-M2`
(euglycemic DKA with a reassuring-looking glucose of 142) and `CKM-004-M2` (chest pressure
that resolved) are the two items designed to elicit it.
"""

misses = results_full[~results_full["correct"]]
if len(misses) == 0:
    print("No misses.")
else:
    for _, row in misses.iterrows():
        direction = "UNDER-triaged" if row["under_triage"] else "OVER-triaged" if row["over_triage"] else "unparseable"
        print(f"{row['message_id']}  expected={row['expected']}  predicted={row['predicted']}  ({direction})")
        #print(f"  ambiguity={row['ambiguity']}  requires_ehr={row['requires_ehr']}")
        print(f"  rationale: {row['rationale'][:220]}\n")

# Confusion matrix over the ordered levels.
order = sorted(TRIAGE_RANK, key=TRIAGE_RANK.get, reverse=True)
print("Confusion (rows = expected, cols = predicted):")
display(pd.crosstab(results_full["expected"], results_full["predicted"])
        .reindex(index=order, columns=order, fill_value=0))

"""### 16. Evaluate the EHR and the guideline contributions

This is the probe's central experiment. Four conditions, same messages, same seed:

| Condition | EHR | RAG |
|---|---|---|
| Free text only (original baseline) | — | — |
| RAG only | — | ✓ |
| EHR only | ✓ | — |
| EHR + RAG | ✓ | ✓ |

The `requires_ehr=True` subset is where the EHR contribution should concentrate. If accuracy
on that subset does not move between "RAG only" and "EHR + RAG", the model is not using the
structured data — regardless of how good the headline number looks.

This runs 4 × 11 = 44 generations; expect several minutes.
"""

conditions = [
#    ("free text only", False, False, False),
#    ("RAG only", False, True, False),
#    ("EHR only", True,  False, False),
    ("EHR + RAG + CKM Staging Known", True,  True, True),
    ("EHR + RAG + CKM Staging Not Known", True,  True, False),
]
ablation_frames = []
for label, use_ehr, use_rag, use_ckm_stage in conditions:
    print(f"\n=== {label} ===")
    df = evaluate(use_ehr=use_ehr, use_rag=use_rag, use_ckm_stage=use_ckm_stage, verbose=False)
    df["condition"] = label
    ablation_frames.append(df)
    print(json.dumps(summarize(df, label), indent=2))

ablation = pd.concat(ablation_frames, ignore_index=True)

print("\n=== Headline ===")
display(pd.DataFrame([summarize(d, d["condition"].iloc[0]) for d in ablation_frames]))

# print("\n=== Accuracy on the requires_ehr subset (the EHR-dependent items) ===")
# display(
#     ablation[ablation["requires_ehr"]]
#     .groupby("condition")["correct"].agg(["mean", "count"])
#     .rename(columns={"mean": "accuracy", "count": "n"})
#     .reindex([c[0] for c in conditions])
# )

# print("\n=== Accuracy by message ambiguity ===")
# display(
#     ablation.pivot_table(index="condition", columns="ambiguity", values="correct", aggfunc="mean")
#     .reindex([c[0] for c in conditions])
#)

"""### Persist the run

Written with the condition, seed, and models attached, so a run stays interpretable after the
Colab session evaporates. Point `RESULTS_PATH` at Drive to keep it.
"""

RESULTS_PATH = "/content/ckm_probe_results.csv"

ablation_out = ablation.copy()
ablation_out["chat_model"] = CHAT_MODEL
ablation_out["embed_model"] = EMBED_MODEL
ablation_out["seed"] = GEN_OPTIONS.get("seed")
ablation_out["corpus_id"] = CORPUS["corpus_id"]
ablation_out.to_csv(RESULTS_PATH, index=False)

print(f"Wrote {len(ablation_out)} rows to {RESULTS_PATH}")

"""---
### 17. Setup RAG extention (future)

**Add documents.** Ingestion is idempotent, so the guideline already in the store is not
re-embedded, and `answer()` and the evaluator immediately span everything ingested:

```python
ingest_documents([
    "/content/kdigo_ckd_guideline.pdf",
    "/content/ada_standards_of_care_2026.pdf",
])
```

**Add patients or messages.** Append to `ckm_patients.json` following the schema in Section 12.
`CASES` rebuilds on reload; no evaluator changes needed. Useful directions: multi-turn threads
(the corpus is single-turn today), messages where the *correct* answer is that the EHR is
stale, and non-English messages.

**Add a triage level.** Add it to `triage_levels` with a rank. `TRIAGE_RANK`, the prompt, and
`severity_distance` all derive from the JSON.

**Tuning**

| Symptom | Lever |
|---|---|
| Answers miss content you know is in the PDF | Raise `RETRIEVE_K`; try `mxbai-embed-large`; re-ingest |
| Answers vague / blend unrelated content | Lower `FINAL_K`; lower `CHUNK_TARGET_CHARS` |
| Retrieved chunks cut mid-argument | Raise `CHUNK_OVERLAP_CHARS` |
| Frequent `parse_failure_rate` | Add `"format": "json"` to `GEN_OPTIONS`; Ollama can constrain decoding |
| Model contradicts sources | Confirm `temperature: 0`; inspect retrieval first |

> Changing `EMBED_MODEL` or the chunking constants invalidates the index. Delete `CHROMA_DIR`
> and re-ingest, or the store will mix two embedding spaces and retrieval will quietly degrade.

**Two limits worth stating in any write-up.** With n=11 messages, a single flip moves accuracy
by 9 points — this corpus is sized to expose failure modes, not to support significance
testing; scale it before making comparative claims. And the expected labels are authored, not
adjudicated by multiple blinded clinicians, so they carry no inter-rater reliability estimate.
Both are fixable, and both are the kind of thing a reviewer asks about first.
"""